### ISSUE TITLE
Status of store deal gets stuck in Announcing for a long time

### ISSUE THREAD

**Issue by han344906637** [filecoin-project/boost#920]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 1.4.0+git.810afec
```

### Describe the Bug

After the number of deals is large, the status of the stored deals will be stuck in Announcing for a long time(hours or even days).
 If the boostd service is restarted, the status of these stuck orders will be changed Becomes full.idx file not found.

### Logging Information

```text
Paused at 'Announcing': failed to add index and announce deal: failed to announce deal to network indexer: failed to announce deal to index provider: failed to get iterable index: failed to get iterable index: open /boostd/boost/dagstore/index/baga6ea4seaqm5ezeirzbgpqultu6mechxhzqriqbrhbzdbildcprsizu4z5amhi.full.idx: no such file or directory
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by dirkmc** [comment]
In the Announcing stage boost
- creates an index of all the blocks in the CAR file
- tells the network indexer that the CAR file has been indexed and waits for the network indexer to ask for the index

The error message means that boost has created an index and stored it, and is now looking for the index at
`/boostd/boost/dagstore/index/baga6ea4seaqm5ezeirzbgpqultu6mechxhzqriqbrhbzdbildcprsizu4z5amhi.full.idx`
But it can't find the file at that location.

Is it possible that the dagstore was moved, or the place where the data for the dagstore was stored has changed?

**Comment by han344906637** [comment]
We did not move or modify the location of the dagstore, and we did not find the corresponding full.idx file in the /boostd/boost/dagstore/index directory.
However, after modifying the "MaxConcurrentIndex=0" in the config.toml file, the problem is solved.
We guess it is because of the default setting that only 5 indexes can be created at the same time. Will the default limit of 5 be too small?

**Comment by han344906637** [comment]
There is no way to fix the deals that have displayed an error status. We try to call "boostd dagstore destroy-shard" and then call "boostd dagstore initialize-shard", but the ”full.idx“ file cannot be rebuilt. Fortunately, it does not affect the encapsulation of stored data.

**Comment by LexLuthr** [comment]
@han344906637 Try to manually register the shard after destroy and see it that works. 
`boostd dagstore register-shard <piece CID>`

**Comment by beck-8** [comment]
```
boostd version 1.5.0+git.dbedffb
```
When I checked the status of the node, I found that the transaction could not be retrieved. Same error, still don't know how to fix it.
![image](https://user-images.githubusercontent.com/34204218/217988257-95e9e125-21a2-4f34-84e9-4b20b210762b.png)
![image](https://user-images.githubusercontent.com/34204218/217988486-df4440dd-2a5c-4f9f-a779-1c618fcca549.png)

**Comment by beck-8** [comment]
```
boostd dagstore destroy-shard <piece CID>
boostd dagstore register-shard <piece CID>
or
boostd dagstore recover-shard
```
It seems to be working, it is gradually recovering, I have observed that the network card is passing a lot of traffic, but the recovery process may take a while.
